version: '3.9'

services:
  web:
    build: .
    container_name: awsite
    ports:
      - "5100:5100"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      PYTHONUNBUFFERED: 1
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mydb_data:/var/lib/postgresql/data

  app:
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

volumes:
  mydb_data: